###############################################################################
# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxy.name }}
  labels:
    app: "{{ .Values.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if and .Values.useOpenshiftSettings .Values.OpenshiftSettings.oauth.useProxy }} 
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: {{ .Values.OpenshiftSettings.oauth.proxyTlsSecretName }} 
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      {{- if and .Values.useOpenshiftSettings .Values.OpenshiftSettings.oauth.useProxy }}
      targetPort: {{.Values.OpenshiftSettings.oauth.proxyPort }}
      port: 443
      {{- else }}
      targetPort: 3000
      port: {{ .Values.proxy.service.port }}
      {{- end }}
      
  selector:
    app: "{{ .Values.name }}"
    release: {{ .Release.Name }}


