###############################################################################
# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2018, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: "{{ .Values.proxy.name }}"
spec:
  secretName: "{{ .Values.volumes.kuiCertsSecretName }}"
  issuerRef:
    name: icp-ca-issuer
    kind: ClusterIssuer
  commonName: "{{ .Values.proxy.name }}"
  dnsNames:
  - kui-proxy.kube-system
  - kui-proxy.kube-system.svc
  - localhost
  - 127.0.0.1