###############################################################################
# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2018, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.name }}
      release: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        heritage: {{ .Release.Service }}
        k8s-app: "{{ .Values.proxy.name }}"
        component: {{ .Values.name }}
        release: {{ .Release.Name }}
      annotations:
        productName: "visual-web-terminal"
        productID: "{{ .Values.proxy.productID }}"
        productVersion: "{{ .Chart.AppVersion }}"
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      nodeSelector:
        master: "{{ .Values.nodeSelector.master }}"
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 60
      containers:
      - name: {{ .Values.proxy.name }}
        image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
        imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: "/status/livenessProbe"
            port: 3000
            scheme: HTTPS
        readinessProbe:
          httpGet:
            path: "/status/readinessProbe"
            port: 3000
            scheme: HTTPS
        env:
        - name: ICP_EXTERNAL_URL
          value: "https://{{ .Values.proxy.clusterIP }}:{{ .Values.proxy.clusterPort }}"
        - name: KUI_INGRESS_PATH
          value: "{{ .Values.proxy.ingressPath }}"
        volumeMounts:
        - name: "{{ .Values.volumeMounts.kuiCertsName }}"
          mountPath: "{{ .Values.volumeMounts.kuiCertsMountPath }}"
        resources:
{{ toYaml .Values.proxy.resources | indent 10 }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
    {{- end }}
      volumes:
      - name: "{{ .Values.volumes.kuiCertsName }}"
        secret:
          secretName: "{{ .Values.volumes.kuiCertsSecretName }}"