###############################################################################
# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################

name: kui-web-terminal
replicaCount: 1
nodeSelector:
  master: 'true'

arch: ""

useOpenshiftSettings: true
OpenshiftSettings:
  clusterURI: han-ocp.os.fyre.ibm.com
  network:
    useRoute: true
    routeName: kui
  oauth:
    mountServiceAccount: true
    serviceAccountSecret: kui-service-account-secret
    useProxy: true
    proxyTlsSecretName: kui-oauth-tls
    proxyPort: 8443
    tokenKey: X-Forwarded-Access-Token
    tokenFromCookie: false
    clientName: kui-oauth-client
    clientSecret: kui-oauth-client-secret

proxy:
  clusterIP: icp-management-ingress
  clusterPort: 8443
  name: kui-proxy
  ingressPath: kui
  service:
    port: 8081
  image:
    repository: quay.io/open-cluster-management
    name: kui-web-terminal
    tag: 3.5.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 128Mi

imageTagPostfix: ""

tolerations:
  - key: "dedicated"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "CriticalAddonsOnly"
    operator: "Exists"

volumes:
  kuiCertsName: "kui-proxy-certs"
  kuiCertsSecretName: "kui-proxy-secret"

volumeMounts:
  kuiCertsName: "kui-proxy-certs"
  kuiCertsMountPath: "/etc/certs"
