###############################################################################
# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kuiextensions.kui.icp.ibm.com
spec:
  group: kui.icp.ibm.com
  names:
    kind: KUIExtension
    listKind: KUIExtensionList
    plural: kuiextensions
    singular: kuiextension
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: KUIExtension is the Schema for the kuiextensions API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: KUIExtensionSpec defines the desired state of KUIExtension
          properties:
            enable:
              type: boolean
            name:
              type: string
            type:
              type: string
            urls:
              items:
                description: KUIExtensionURL defines the url and other information
                  which will be used for KUI to download and install
                properties:
                  arch:
                    type: string
                  hash:
                    type: string
                  os:
                    type: string
                  url:
                    type: string
                required:
                - hash
                - url
                type: object
              type: array
            version:
              type: string
          required:
          - enable
          - name
          - type
          - urls
          - version
          type: object
        status:
          description: KUIExtensionStatus defines the observed state of KUIExtension
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
