apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ .Values.serviceAccount.serviceAccountSecret }} 
  labels:
    app: "{{ .Values.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations: 
    kubernetes.io/service-account.name: {{ .Values.serviceAccount.serviceAccountName }}
