apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ .Values.serviceAccount.roleName }}
rules:
- apiGroups:
  - kui.icp.ibm.com
  resources:
  - '*'
  verbs:
  - "get"
  - "list"
  - "watch"
