apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: {{ .Values.serviceAccount.serviceAccountName }}
  labels:
    app: "{{ .Values.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}

