kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.serviceAccount.roleBindingName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.serviceAccountName }}
roleRef:
  kind: Role
  name: {{ .Values.serviceAccount.roleName }}
  apiGroup: rbac.authorization.k8s.io
