###############################################################################
# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################

name: mcm-kui
replicaCount: 1
nodeSelector:
  master: 'true'

arch: ""
serviceAccount:
  roleName: kui-initcontainer
  serviceAccountName: kui-initcontainer
  roleBindingName: kui-initcontainer
  serviceAccountSecret: kui-initcontainer-secret

enableExtensions: true
extensions:
  downloadPath: /Downloads
  name: mcm-kui-init
  image:
    repository: ibmcom/mcm-kui-init
    tag: 3.5.0
    pullPolicy: IfNotPresent

proxy:
  clusterIP: icp-management-ingress
  clusterPort: 8443
  name: kui-proxy
  ingressPath: kui
  service:
    port: 8081
  image:
    repository: ibmcom/mcm-kui-proxy
    tag: 3.5.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 128Mi

tolerations:
  - key: "dedicated"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "CriticalAddonsOnly"
    operator: "Exists"

volumes:
  kuiCertsName: "kui-proxy-certs"
  kuiCertsSecretName: "kui-proxy-secret"

volumeMounts:
  kuiCertsName: "kui-proxy-certs"
  kuiCertsMountPath: "/etc/certs"
